### PR TITLE
[EAOC-9816] - Removal of AspectJ

### PR DESCRIPTION
**Pull request by KJSweeneyMetova**
Removal of AspectJ
Update Configuration Property Values
Update Dependencies
Update UI Elements

### CODE REVIEW

**Review by HugoTealeaf — APPROVED** [review]
Looks good to me 👍

**Comment by KJSweeneyMetova** [comment]
Please take a careful look at the properties that we updated in our meeting today to make sure that everything is okay.  I changed a few back (e.g., ClickEventEnabled = false, cookiesecure = false)

**Comment by cyangibm** [comment]
@HugoTealeaf After review, please merge & delete branch as we discussed before, thanks.

**Comment by cyangibm** [comment]
Merged, need to investigate a few issues reported by Kim.

**Pull request merged**
